### ISSUE TITLE
Use myself dataset?

### ISSUE THREAD

**Issue by happsky** [ahmetius/diffusion-retrieval#1]
How can I use myself dataset?

**Comment by ahmetius** [comment]
We hope that our test script run_test.m can guide you with that. Dataset vectors are loaded in load_vectors.m, so if you already have computed descriptors for your dataset, you can modify this file. If you need to extract descriptors for your dataset, we used the [CNN-Imageretrieval](https://github.com/filipradenovic/cnnimageretrieval) repository for the feature extraction.
