### ISSUE TITLE
Incorrect coding?

### ISSUE THREAD

**Issue by underfitting** [ahmetius/diffusion-retrieval#3]
I think findtrunc.m is incorrectly written.

 `     [knn, ~] = knn_wrap(v, qv, k,100);`
`       f = find(ismember(imids,knn));`

`knn`      : knn index of v
`imids`   : image_id list 

then, I think `ismember(imids,knn)` is matching `vector_id` list and `image_id` list.

**Comment by ahmetius** [comment]
The code is correct. We are truncating the regional affinity matrix by keeping regions of top ranked images. `knn` contains the top ranked images for the query. Each entry of `imids` is the image id of the corresponding region. Therefore `find(ismember(imids,knn))` returns the regions of the top ranked images.

**Comment by underfitting** [comment]
>knn contains the top ranked images for the query

If `knn` contains image_ids, do you assume that each image is represented by one vector?
Then, the shape of `Vextra` is `d x number of images`, right? (not `d x number of vectors`?)

**Comment by ahmetius** [comment]
Yes, initial shortlist (`knn`) is created with global descriptors (one vector per image).

**Comment by underfitting** [comment]
Oh, I get it!
If so, your code is correct.
